-- CreateEnum
CREATE TYPE "MealPlan" AS ENUM ('ROOM_ONLY', 'BREAKFAST_INCLUDED', 'HALF_BOARD', 'FULL_BOARD');

-- AlterTable
ALTER TABLE "Booking" ADD COLUMN     "extraBed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "mealPlan" "MealPlan" NOT NULL DEFAULT 'ROOM_ONLY',
ADD COLUMN     "roomsCount" INTEGER NOT NULL DEFAULT 1;
